version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@sswOrd123
      - MSSQL_PID=Developer
    ports:
      - "1434:1434"  # Cambiado a 1434 que es el puerto estándar
    volumes:
      - ./scripts-sql:/scripts
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "P@sswOrd123" -Q "SELECT 1" || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
  command: 
    - /bin/bash
    - -c
    - |
      # Iniciar SQL Server en segundo plano
      /opt/mssql/bin/sqlservr &
      # Esperar a que SQL Server esté listo
      sleep 30
      # Ejecutar scripts SQL
      /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P P@sswOrd123 -i /scripts/SkyNurceCrear.sql
      /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P P@sswOrd123 -i /scripts/SkyNurceTiposDatos.sql
      /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P P@sswOrd123 -i /scripts/SkyNurce.sql
      # Mantener el contenedor en ejecución
      tail -f /dev/null
  backend:
    build:
      context: .
    container_name: node_backend
    environment:
      - NODE_ENV=production
      - PORT=4500
      - DB_HOST=db  # Usar el nombre del servicio como host
      - DB_USER=SA
      - DB_PASSWORD=P@sswOrd123
      - DB_PORT=1434  # Puerto estándar
    ports:
      - "4500:4500"
    depends_on:
      db:
        condition: service_healthy